/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// WicedLED_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_WICEDLED                       0x3a, 0xa5, 0xbf, 0x8c, 0xd0, 0x14, 0x4f, 0x50, 0x86, 0x1b, 0x73, 0xf3, 0x0f, 0x93, 0x62, 0x8b
#define __UUID_WICEDLED_LED                   0xc6, 0x36, 0xfb, 0x3e, 0x43, 0x43, 0x4e, 0x67, 0xbc, 0xe8, 0x9e, 0xa1, 0xd7, 0x23, 0x6d, 0xcc

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                   0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME       0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE 0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE        0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE  0x0018

// ***** Primary Service 'WicedLED'
#define HDLS_WICEDLED                         0x0028
// ----- Characteristic 'LED'
#define HDLC_WICEDLED_LED                     0x0029
#define HDLC_WICEDLED_LED_VALUE               0x002A

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table wicedled_gatt_db_ext_attr_tbl[];
extern const uint16_t wicedled_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
